Add Power BI refresh
Azure/adx-automation-agent pull request #13
Opened 2018-04-10 02:23 UTC by mcardosos

2018-04-10 17:48 UTC, troydai requested changes
Let's move the logic into the service as a micro-service.

2018-04-11 22:34 UTC, troydai requested changes

2018-04-11 22:34 UTC, troydai commented on reportutils/powerbi.go
> +	if run.IsOfficial() {
I would do this to reduce the indentation:
```
if !run.IsOfficial() {
    common.LogInf("....")
    return
}

// rest of the logic when the run is official
```

2018-04-11 22:34 UTC, troydai commented on reportutils/common.go
> +var httpClient = &http.Client{}
Is it a bit overkill?

2018-04-11 22:34 UTC, troydai commented on reportutils/powerbi.go
> +			fmt.Sprintf("http://%s/powerbi", common.DNSNamePowerBIService),
This is not related, but I think this is a poor service resource name.

`POST /PowerBIServce/powerbi` doesn't necessarily tell the reader anything about what this action is doing. It is not a straightforward resource name. Maybe we can review the name a bit later.

2018-04-11 22:37 UTC, mcardosos commented on reportutils/powerbi.go
> +			fmt.Sprintf("http://%s/powerbi", common.DNSNamePowerBIService),
What about `reportrefresh` ?

2018-04-11 23:18 UTC, mcardosos commented on reportutils/powerbi.go
> +			fmt.Sprintf("http://%s/powerbi", common.DNSNamePowerBIService),
Fixed

2018-04-12 05:58 UTC, mcardosos commented on reportutils/common.go
> +var httpClient = &http.Client{}
Fixed

2018-04-12 15:51 UTC, troydai submitted a review, later dismissed
Will till the service is merged and redeployed.

2018-04-12 15:51 UTC, troydai commented on Gopkg.toml
> +  name = "github.com/Azure/go-autorest"
I didn't see this reference in the source code. Is it needed?

2018-04-12 16:20 UTC, mcardosos commented on Gopkg.toml
> +  name = "github.com/Azure/go-autorest"
Nope, leftover from previous implementation. Removed :)

2018-04-12 17:57 UTC, mcardosos commented
Deployed

2018-04-12 21:34 UTC, troydai approved these changes

2018-04-12 21:34 UTC, merged